### ISSUE TITLE
[FEATURE] change naming folder GC to gamecube

### ISSUE THREAD

**Issue by Sebio1980** [TigraTT-Driver/shinretro#36]
**Is your feature request related to a problem? Please describe.**
for different retrogaming operating system the nintendo gamecube system folder is named gamecube and not gc. found in roms/gamecube

**Describe the solution you'd like**
Is it possible to change the name "gc" in the /assets/collections folder to "gamecube"
Thanks

**Describe alternatives you've considered**

**Additional context**

**Comment by TigraTT-Driver** [comment]
sure i think i overlooked something. the official pegasus naming scheme even recommends gc. usually i stick to this one

**Comment by Sebio1980** [comment]
ok thank you for this answer.
