### ISSUE TITLE
[FEATURE] change naming folder gameandwatch to gw

### ISSUE THREAD

**Issue by Sebio1980** [TigraTT-Driver/shinretro#37]
**Is your feature request related to a problem? Please describe.**
for different retrogaming operating system the game and watch system folder is named gw and not gameandwatch. found in roms/gw

**Describe the solution you'd like**
Is it possible to change the name "gameandwatch" in the /assets/collections folder to "gw"
Thanks

**Describe alternatives you've considered**

**Additional context**

**Comment by TigraTT-Driver** [comment]
the official pegasus naming scheme recommends gameandwatch  as a common plattform name. usually i stick to this one so so that there are no problems for the user when changing the theme https://pegasus-frontend.org/docs/user-guide/meta-files/#metadata

**Comment by Sebio1980** [comment]
ok thank you for this answer.
