### ISSUE TITLE
[BUG] some systems have their logo with their original name

### ISSUE THREAD

**Issue by Sebio1980** [TigraTT-Driver/shinretro#38]
**Describe the bug**
some systems have their logo with their original name and therefore the code has no possibility to find the logo.

**To Reproduce**
1. Go to /assets/collections/
2. colecovision/colecovision.svg -> See error the good name is logo_mono.svg
3. gameandwatch/gameandwatch.svg -> See error the good name is logo_color.svg
4. msxturbor/logo_color (copy).svg.svg -> See error the good name is logo_mono.svg

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - OS: [e.g. android]
 - Version [e.g. 10]
 - GPU [nvidia]

**Additional context**

**Comment by TigraTT-Driver** [comment]
thx. fixed it :+1:
