### ISSUE TITLE
[FEATURE] Update/change naming « collections » to « systems »

### ISSUE THREAD

**Issue by Sebio1980** [TigraTT-Driver/shinretro#39]
**Is your feature request related to a problem? Please describe.**
Update/change naming « collections » to « systems » because in this page you select the systems « PC or arcade or consols or android », the collections it’s a type for category definition a lot systems

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TigraTT-Driver** [comment]
since the collection screen now can show custom collections like 'Mario' i think this is obsolute
