### ISSUE TITLE
[BUG} Pal Color Logo on collection menu apparears full black

### ISSUE THREAD

**Issue by HunkDeath** [TigraTT-Driver/shinretro#44]
Hi, on the last version of the theme, there is a bug when i choose pal color logo for the collection menu. Logo appears totally black on the majortiy of systems. Only SNES, Megadrive and Atari 5200 are correct (colorfull logo). Thanks for your help.

![Logo bug](https://user-images.githubusercontent.com/93476939/185223358-04b04fe2-1166-4621-9fd6-d695475328a1.png)

![Logo ok](https://user-images.githubusercontent.com/93476939/185223424-c462ce10-4b04-436f-866e-fe79843c9729.png)

![parameter](https://user-images.githubusercontent.com/93476939/185223440-a56a1d98-e6f4-430b-8833-93f2cd9466c1.png)

**Device**
 - OS: Windows 10 21H2
 - Pegasus Version : pegasus-fe_alpha16-42-g996720eb_win-mingw-static
 - GPU : AMD RX 6600

**Comment by TigraTT-Driver** [comment]
Hi @HunkDeath
Looks like it's loading the monochrom logos.
Unfortunatly I can't replicate your issue on my machines (but i only use Linux). But something else seems to be wrong with your setup too. Windows collection should not have the IBM manufacturer logo. It should have the modern Microsoft logo. Did you do some modifications on the theme? Can you try to fresh Install the theme:
- delete your shinretro folder inside the Pegasus theme folder or move it somewhere else
- delete (or rename) your shinretro.json inside the Pegasus theme_settings folder
- Download the theme and and extract it to your themes folder

**Comment by HunkDeath** [comment]
Hi, i tried with a fresh install and i have the same problem

![bug logo color 2](https://user-images.githubusercontent.com/93476939/185743832-155a5b88-75d0-4f89-854c-3daa1c83124b.png)
![bug logo color 3](https://user-images.githubusercontent.com/93476939/185743841-8b90df22-0b8b-471f-93e6-4e1e6ef7c783.png)

I looked the svg file in assets folder and i find something. It seems that the bug has something to do with the size of the logo in pixel

![logo marche pas](https://user-images.githubusercontent.com/93476939/185743896-e52f7e5a-6ba6-47e1-81ea-f1b8777b8cc8.png)
![logo marche](https://user-images.githubusercontent.com/93476939/185743900-4ead783f-595c-41d3-82a9-fdfc85d80b4f.png)

I tried to reduce the size of logos concerned but unfortunately, the problem stay here.

**Comment by TigraTT-Driver** [comment]
![logo_color](https://user-images.githubusercontent.com/93423624/185762300-55772d8f-d7d8-4636-9431-adb015038bb1.svg)
Can you try to use attached svg?

**Comment by HunkDeath** [comment]
Ok, it works

![Logo ok](https://user-images.githubusercontent.com/93476939/185764014-bd8948ee-fdb6-40e4-ac42-878295f0dcab.png)

Did you reduce the size of logo ?

**Comment by TigraTT-Driver** [comment]
no the pixel size is not the problem. i transformed the content of the svg in a single path object with a color fill.
Former it had multiple grouped paths and css styling. You can see the difference very well  if you open the two svg with a text editor. I don't know if and how you can do this in batch, probably need to do this per hand for every svg.

**Comment by TigraTT-Driver** [comment]
@HunkDeath I've updated all the svg graphics and applied the same changes like on the atari 2600 test. can you try it again?

**Comment by HunkDeath** [comment]
Ok i tested on different configuration
 - Pal Color logo : Everything it's ok. No more bugs
 - Pal Monochrome logo : No bug
 - NTSC Color logo : No bug
 - NTSC Monochrome : No bug
 - NTSCJ Color : 1 bug found on Sega Saturn
 - NTSCJ Monochrome : No bug

I don't have so many systems so i couldn't tested all systems of theme.

**Comment by TigraTT-Driver** [comment]
missed one.
I have corrected the affected saturn logo and checked again whether I have edited each.
Think thereby it should now be correct
