### ISSUE TITLE
[BUG}

### ISSUE THREAD

**Issue by kukufeng** [TigraTT-Driver/shinretro#46]
My name is kukufeng, I am from China, I have added Chinese translation, two files are packaged and uploaded，it is below

[Language.zip](https://github.com/TigraTT-Driver/shinretro/files/9509406/Language.zip)

**Comment by kukufeng** [comment]
my link

https://github.com/kukufeng?tab=repositories

**Comment by TigraTT-Driver** [comment]
hi @kukufeng,
i've added your translations to the upcoming version.
since new menu items will be added with the next version, can you translate them as well?

**Comment by kukufeng** [comment]
No problem, I will translate in time
