### ISSUE TITLE
[Feat.] make logo(wheel) above video on home screen toggleable

### ISSUE THREAD

**Issue by Sebio1980** [TigraTT-Driver/shinretro#57]
**Describe the bug**
In the home, when I am on a thumbnail of a game, the video of this one launches but the logo remains displayed.

**To Reproduce**
1. in option activated auto launch video
2. Go to 'Home'
3. Select highlight 'game'
4. video launch but the logo(wheel) always printed
<a href="https://zupimages.net/viewer.php?id=22/41/pxhz.jpg"><img src="https://zupimages.net/up/22/41/pxhz.jpg" alt="" /></a>
**Expected behavior**
In the settings you can choose whether or not to display the logo when the video starts.

**Screenshots**
<a href="https://zupimages.net/viewer.php?id=22/41/t9ee.jpg"><img src="https://zupimages.net/up/22/41/t9ee.jpg" alt="" /></a>

**Device (please complete the following information):**
 - OS: [pixL-Linux] on PC 64 Bits
 - Version [e.g. 10]
 - GPU : GeForce GTX 1080 mobile
 - CPU : I7-6820
 - System Storage device : USB box SSD M.2

**Additional context**
I have scraped all media (19)
<a href="https://zupimages.net/viewer.php?id=22/41/2qmq.png"><img src="https://zupimages.net/up/22/41/2qmq.png" alt="" /></a>

Thank you for help

**Comment by TigraTT-Driver** [comment]
This ist currently a design choice and the game logo ist always shown above the video. I think a setting to change the behaviour can be made.

**Comment by Sebio1980** [comment]
Thank you for taking into account an option in the settings to display or not the logo over the video. Have a good day
