### ISSUE TITLE
[BUG] system without logo(wheel)

### ISSUE THREAD

**Issue by Sebio1980** [TigraTT-Driver/shinretro#58]
**Describe the bug**
I have a lot of system without logo(wheel) in menu system

**To Reproduce**
1. Go to 'collection'
2. slide 'system'
3. See error not print system on "top right" and/or "below the number of games"

**Expected behavior**
See the logo(wheel)

**Screenshots**
Jaguar:
<a href="https://zupimages.net/viewer.php?id=22/41/l9cr.jpg"><img src="https://zupimages.net/up/22/41/l9cr.jpg" alt="" /></a>
<a href="https://zupimages.net/viewer.php?id=22/41/m9z6.jpg"><img src="https://zupimages.net/up/22/41/m9z6.jpg" alt="" /></a>

Chihiro:
<a href="https://zupimages.net/viewer.php?id=22/41/uwgd.jpg"><img src="https://zupimages.net/up/22/41/uwgd.jpg" alt="" /></a>
<a href="https://zupimages.net/viewer.php?id=22/41/p2a7.jpg"><img src="https://zupimages.net/up/22/41/p2a7.jpg" alt="" /></a>

Doom:
<a href="https://zupimages.net/viewer.php?id=22/41/h48o.jpg"><img src="https://zupimages.net/up/22/41/h48o.jpg" alt="" /></a>
<a href="https://zupimages.net/viewer.php?id=22/41/m8fw.jpg"><img src="https://zupimages.net/up/22/41/m8fw.jpg" alt="" /></a>

Fbneo:
<a href="https://zupimages.net/viewer.php?id=22/41/drk7.jpg"><img src="https://zupimages.net/up/22/41/drk7.jpg" alt="" /></a>

MAME:
<a href="https://zupimages.net/viewer.php?id=22/41/ihiw.jpg"><img src="https://zupimages.net/up/22/41/ihiw.jpg" alt="" /></a>

SEGA MODEL 3:
<a href="https://zupimages.net/viewer.php?id=22/41/8s93.jpg"><img src="https://zupimages.net/up/22/41/8s93.jpg" alt="" /></a>
<a href="https://zupimages.net/viewer.php?id=22/41/ddlc.jpg"><img src="https://zupimages.net/up/22/41/ddlc.jpg" alt="" /></a>

SEGA NAOMI 2:
<a href="https://zupimages.net/viewer.php?id=22/41/jd5l.jpg"><img src="https://zupimages.net/up/22/41/jd5l.jpg" alt="" /></a>
<a href="https://zupimages.net/viewer.php?id=22/41/vn50.jpg"><img src="https://zupimages.net/up/22/41/vn50.jpg" alt="" /></a>

NAOMI:
<a href="https://zupimages.net/viewer.php?id=22/41/eru8.jpg"><img src="https://zupimages.net/up/22/41/eru8.jpg" alt="" /></a>

NAOMI CD:
<a href="https://zupimages.net/viewer.php?id=22/41/u24m.jpg"><img src="https://zupimages.net/up/22/41/u24m.jpg" alt="" /></a>

QUAKE:
<a href="https://zupimages.net/viewer.php?id=22/41/liaj.jpg"><img src="https://zupimages.net/up/22/41/liaj.jpg" alt="" /></a>
<a href="https://zupimages.net/viewer.php?id=22/41/vw0x.jpg"><img src="https://zupimages.net/up/22/41/vw0x.jpg" alt="" /></a>

QUAKE 2:
<a href="https://zupimages.net/viewer.php?id=22/41/xt7x.jpg"><img src="https://zupimages.net/up/22/41/xt7x.jpg" alt="" /></a>
<a href="https://zupimages.net/viewer.php?id=22/41/qrw0.jpg"><img src="https://zupimages.net/up/22/41/qrw0.jpg" alt="" /></a>

wolfenstein 3D:
<a href="https://zupimages.net/viewer.php?id=22/41/9s62.jpg"><img src="https://zupimages.net/up/22/41/9s62.jpg" alt="" /></a>
<a href="https://zupimages.net/viewer.php?id=22/41/muon.jpg"><img src="https://zupimages.net/up/22/41/muon.jpg" alt="" /></a>

XBOX:
<a href="https://zupimages.net/viewer.php?id=22/41/nno9.jpg"><img src="https://zupimages.net/up/22/41/nno9.jpg" alt="" /></a>

**Device (please complete the following information):**
 - OS: [e.g. android]
 - Version [e.g. 10]
 - GPU [nvidia]

**Additional context**

**Comment by TigraTT-Driver** [comment]
think its done.
atari jaguar already exists. it's called atarijaguar in pegasus.
The black boxed manufacturer logos should be fixed ( i think that's been what you wanted to show with xbox, final burn neo, mame). other shown collections i've added artwork. see cb041de

**Comment by Sebio1980** [comment]
hello, you don't find picture for Quake 2
and the good folder in roms for the ports games are 
roms/ports/{games}
<a href="https://zupimages.net/viewer.php?id=22/42/ndo9.png"><img src="https://zupimages.net/up/22/42/ndo9.png" alt="" /></a>
