### ISSUE TITLE
[BUG] filter not function with pad in linux OS

### ISSUE THREAD

**Issue by Sebio1980** [TigraTT-Driver/shinretro#59]
**Describe the bug**

**To Reproduce**
1. Go to 'game menu'
2. Click on 'Y' for pop-up filter menu
3. not possible to select other filter

**Expected behavior**
not possible to select other filter

**Screenshots**
[video](https://fromsmash.com/W6Y1vwAuz5-ct)

**Device (please complete the following information):**
 - OS: [pixL-Linux] on PC 64 Bits
 - Version [e.g. 10]
 - GPU : GeForce GTX 1080 mobile
 - CPU : I7-6820
 - System Storage device : USB box SSD M.2

**Additional context**
If you need the last version pixL-OS plz contact in discord.

**Comment by TigraTT-Driver** [comment]
I can't reproduce the problem on my side and I only use Linux machines. At first sight it looks like the input might be caught by the input mask for the search. Do you have the problem with other themes which have an input mask for the search, e.g. the default theme Pegasus-Grid or GameOS?

**Comment by Sebio1980** [comment]
Hello, I have the same problem on "pegasus-theme-grid-master".
I use an official xbox one series pad.

After having discussed with my team, it is normal that my "virtual keyboard" does not work with your theme and the others.

As our system is a fork of "Recalbox Linux-ubuntu-18.04".

It is necessary to make an addition in the theme that we have described in this page: https://doc.pixl-os.com/dev-pegasus-theme-comment-integrer-le-clavier-virtuel-de-pegasus/ and which works because we made the implementation in pegasus of the functional binding.

To see if this can be basic in your theme?
I like your theme and I would like to make it one of our 2 main themes in addition to the gameOS that we have already modified for our users.

**Comment by TigraTT-Driver** [comment]
@Sebio1980  I really like the on screen keyboard. Also the design of your keyboard looks very well. I'd gladly would put it in my theme. 
Unfortunately I don't speak French and do not get everything of the documentation with the help of google translate (probably some gets incorrectly translated).
Does this work with the mainline pegasus builds or only with your fork?
If later can you upstream it so everyone benefits from it?

**Comment by Sebio1980** [comment]
@TigraTT-Driver I will see to translating the entire web page into clean English.

It only works in our fork because we have implemented in our Pegasus fork the virtual keyboard function which is not original and our fork has some optimizations for the start.
We already proposed optimizations for gameOS and Pegasus but it wasn't generic enough :(

If in the future you want to see the branches that we are starting to do for your theme [Shinretro-pixL](https://github.com/pixl-os/shinretro)
Currently I am working to implement [Retroachievements](https://doc.pixl-os.com/api-pegasus-pour-les-retroachievements/) and [NETPLAY](https://doc.pixl-os.com/le-netplay-dans-pegasus/).

**Comment by Sebio1980** [comment]
update information: 
We use QT's virtual keyboard, but that was not easy to integrate. And we added a component in our OS to make it run, that's why Matthias (Pegasus) does not integrate it, because it takes a particular component to install in the OS.

**Comment by Sebio1980** [comment]
Hello, this issue is solved by this pull request : https://github.com/TigraTT-Driver/shinretro/pull/63
but it's work only for my fork pegasus-fe
